import "./globals.css"
import { Geist, Geist_Mono } from "next/font/google"
import { Metadata } from "next"
import {
  ClerkProvider,
  Show,
  SignInButton,
  SignUpButton,
  UserButton,
} from "@clerk/nextjs"
import { ThemeProvider } from "next-themes"
import { cn } from "@/lib/utils.ts"

const geist = Geist({ subsets: ["latin"], variable: "--font-sans" })

export const metadata: Metadata = {
  title: "Easy English Academy",
  description: "Generated by Alim",
}

const fontMono = Geist_Mono({
  subsets: ["latin"],
  variable: "--font-mono",
})

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <ClerkProvider afterSignOutUrl="/sign-in">
      {/* <header className="flex h-16 items-center justify-end gap-4 p-4"> */}
      <html
        lang="en"
        suppressHydrationWarning
        className={cn(
          "antialiased",
          fontMono.variable,
          "font-sans",
          geist.variable
        )}
      >
        <body>
          <ThemeProvider>
            {/* <Show when="signed-in"> */}
              <SignInButton />
            {/* </Show> */}
            {/* <Show when="signed-out"> */}
              <SignUpButton />
            {/* </Show> */}
            {children}
          </ThemeProvider>
        </body>
      </html>
      {/* </header> */}
    </ClerkProvider>
  )
}
